<a href="https://colab.research.google.com/github/udev22/udev22_sort/blob/main/NumPy_Kutubhonasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpylogo.svg

Malumotlarning barchasi shu saytlar va YouTube orqali yigilgan !!!

[***NumPy***](https://https://numpy.org/)

[***NumPy Matrix Multiplication***](https://www.digitalocean.com/community/tutorials/numpy-matrix-multiplication)

[***Python NumPy - Tutorial for Beginners***](https://www.youtube.com/watch?v=QUT1VHiLmmI)

[***Python NumPy - Полный Курс для Начинающих***](https://www.youtube.com/watch?v=IWezobwAC-U)

Asosiy olingan malumotlar: [***Array creation routines***
](https://numpy.org/doc/stable/reference/routines.array-creation.html)

# **NumPyga Kirish va NumPy nima?**
**NumPy** - bu massivlar bilan ishlash uchun ishlatiladigan Python kutubxonasi.
Shuningdek, u chiziqli algebra, matritsalar bilan ishlash uchun tayyor funktsiyalariga ega kutubxona.

**NumPy** 2005 yilda Travis Oliphant tomonidan yaratilgan. Bu ochiq manbali loyihadir va siz uni erkin ishlatishingiz mumkin.

**NumPy** raqamli Python degan ma'noni anglatadi.

## **Nima uchun NumPydan foydalanish kerak?**
**Pythonda** massivlar maqsadiga xizmat qiladigan ro'yxatlar bor, lekin ularni qayta ishlash sekin.

**NumPy** an'anaviy Python ro'yxatlaridan 50 barobar tezroq ishlashini maqsad qigan.

## **Nima uchun NumPy ro'yxatlardan tez?**
NumPy massivlari ro'yxatlardan farqli o'laroq xotirada uzluksiz bir joyda saqlanadi, shuning uchun jarayonlar ularga juda samarali kirishi va boshqarishi mumkin. Bundan tashqari, u eng yangi protsessor arxitekturasi bilan ishlash uchun optimallashtirilgan.

# **NumPy qaysi tilda yozilgan?**
**NumPy** Python kutubxonasi va qisman Pythonda yozilgan, lekin tez ishlashini talab qiladigan qismlarning aksariyati **C** yoki **C++** da yozilgan.

## **NumPy kod bazasi qayerda?**
**NumPyning** kodlari github omborida joylashgan https://github.com/numpy/numpy

***NumPy kutubhonasini chaqirib olamiz!!!***

In [ ]:
import numpy as np

***Asoslari Array yaratish***


In [ ]:
a = np.array([1,2,3,4], dtype='int32')  #bir olchamli array 
print(a)                               #agar typeni bersangiz hotiradan kerakli joyni ajratadi

[1 2 3 4]


In [ ]:
b = np.array([[1,2,3,4], [5,6,7,8]])  #ikki olchamli array
print(b)                              #agar typni bermasangiz aftomatik kichkina malumot uchun ham katta joy ajratadi

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.ndim  #massivning nechchi olchamliligini aniqlab beradi

2

In [ ]:
b.shape  #massivning nechta ustun va satrlari borligini aniqlab beradi

(2, 4)

In [ ]:

a.dtype  #kiritgan qiymatimiz qaysi typga tegishli ekanligini abiqlab beradi

dtype('int32')

In [ ]:
a.itemsize  #kiritilgan qiymatning 

4

In [ ]:
a.nbytes  #kiritilgan qiymatning xotiradan qancha joy egallashini korsatadi baytlarda yani 4ta-element 6-bayt

16

In [ ]:
a.size  #kiritilgan qiymatning nechta elementi borligini aniqlab beradi

4

***Arraylar ustida amallar bajaramiz***

In [ ]:
a2 = np.array([1,2,3,4,5])  #bir olchovli array
print(a)

[1 2 3 4]


In [ ]:
b2 = np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])  #ikki olchovli array
print(b2)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [ ]:
c2 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])  #uch olchovli array
print(c2)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [ ]:
c2[1,1,:]  #uch olchovli massiv ham qolganlaridaka chaqiriladi

array([13, 14, 15, 16])

In [ ]:
b2[1,5]  #agra massivning biron elementini olmoqchi bolsak uning kardinatasini yani turgan joyini beramiz
         #eslatib otaman python array massivda bolganidek birinchida turgan element: 0-dan boshlab sanaladi

15

In [ ]:
b2[1,:]  #ikki nuqta bu-satr yoki ustunning barcha elementlarini chiqarib beradi

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

***Endi Massiv elementining qiymatini ozgartirishi koramiz:***
Extiyod boling qiymat ozgarganda Massivning siz korsatgan qiymati ham ozgarib Massiv ozgargan holda chiqadi yoki ishlatasiz.
Lekin bunga ham yechim bor albatta bu ***copy*** 

In [ ]:
b2[1,5] = 60  #sezgan bolsangiz massiv elementini chaqirib uni ozgartirdik va ekranga chiqargan vaqtda massivda ozgarish sodir boldi
print(b2)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 60 16 17 18]]


***Turli hil Massivlarni ishlatish***

In [ ]:
np.zeros((3,5))  #korib turibsizki massiv sheapni bergan holda 0-bilan toldirilgan massiv yaraib beradi

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,5))  #korib turibsizki massiv sheapni bergan holda 1-bilan toldirilgan massiv yaraib beradi

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,5), 17)  #yoki bolmasa massiv sheapni bergan holda full-sozidan foydalanib hohlagan qiymat bilan toldirishingiz mumkin

array([[17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17],
       [17, 17, 17, 17, 17]])

In [ ]:
np.random.rand(3,5)  #massiv sheapni bergan holda random sozi yordamida, massivni ichini tasodifi sonlar bilan toldiramiz

array([[0.35948055, 0.12256993, 0.11371187, 0.69489258, 0.48533963],
       [0.08795241, 0.15193072, 0.60829247, 0.3500105 , 0.23079922],
       [0.52975608, 0.42502329, 0.46468715, 0.51891273, 0.9222236 ]])

In [ ]:
np.random.randint(0,99, size=(3,5))  #agar massivni intejir sonlar bilan toldirmoqchi bolsak randint-sozidan foydalanamiz
                                     #birinchi kelgan ikkita qiymat yani 0-va-99 bu-massivni toldirish uchun foydalanadigan sonlarning oraligi
                                     #ikkinchi kelgan size ichidagi sonlar massiv ustun, va satrlaridir

array([[17, 26, 35, 10, 61],
       [35, 98, 57, 54, 42],
       [61, 40, 66, 65,  6]])

In [ ]:
np.identity(3)  #identitey-matrikslar diyaganali faqat birlardan iborat boladi massiv ham kvadrat matritsa boladi 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

***Endi Massivlardan dublikat olishni yani nusxalashni koramiz:***
Tepada aytganimizdek endi ***copy***-dan foydalanamiz.

In [ ]:
a3 = np.array([1,2,3,4])  #korganingizdek arraylarni yani massivlarni oz-oziga nusxalash
qq = a3.copy()
print(qq)

[1 2 3 4]


***Massivlar ustida amallarni***

In [ ]:
a4 = np.array([1,2,3,4])
print(a4)

[1 2 3 4]


In [ ]:
b4 = np.array([5,6,7,8])
print(b4)

[5 6 7 8]


In [ ]:
print(a4 + 3)  #massivni chaqirgan holda oddiy usulda hohlagan qiymatni Massivning har bitta elementga qo'shish mumkin
print(b4 + 3)
print(a4 - 3)  #massivni chaqirgan holda oddiy usulda hohlagan qiymatni Massivning har bitta elementidan ayrishi mumkin
print(b4 - 3)
print(a4 * 3)  #massivni chaqirgan holda oddiy usulda hohlagan qiymatni Massivning har bitta elementga ko'paytirish mumkin
print(b4 * 3)
print(a4 / 3)  #massivni chaqirgan holda oddiy usulda hohlagan qiymatni Massivning har bitta elementini bo'lishi mumkin
print(b4 / 3)

[4 5 6 7]
[ 8  9 10 11]
[-2 -1  0  1]
[2 3 4 5]
[ 3  6  9 12]
[15 18 21 24]
[0.33333333 0.66666667 1.         1.33333333]
[1.66666667 2.         2.33333333 2.66666667]


In [ ]:
print(a4 + b4)  #massivlarni bir-biriga qoshish
print(a4 - b4)  #massivlarni bir-biriga ayrish
print(a4 * b4)  #massivlarni bir-biriga ko'paytirish
print(a4 / b4)  #massivlarni bir-biriga bo'lish

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
print(a4**2)  #massivimizning har bir elementini kvadratka kotarishi
print(b4**2)

[ 1  4  9 16]
[25 36 49 64]


In [ ]:
np.cos(a4)  #math 

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

***UDEV22__UDEV22__UDEV22__UDEV22__UDEV22__UDEV22__UDEV22__UDEV22***

In [ ]:
a5 = np.ones((3,3))
print(a5)

b5 = np.full((3,2),2)
print(b5)

np.matmul(a5,b5)  #matmul-Multiplication yani massivlarni bir-biriga ko'paytirish

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [ ]:
print(np.max(a3))  #massivimizning eng katta elementini topish
print(np.min(a4))  #massivimizning eng kichkina elementini topish

4
1


In [ ]:
a6 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(np.sum(a6))  #massivimizning elementlar yigindisini hisoblab beradi

55


In [ ]:
np.sum(a6, axis=0)  #massivning umumiy ustunlarini summasini hisoblashda axis-yani ustunlar chaqirish uchun ishlatiladi

array([ 7,  9, 11, 13, 15])

In [ ]:
r1 = np.array([1,2,3,4,5])
r2 = np.array([6,7,8,9,10])

np.vstack([r1,r2,r1,r2])  #korganingizdek bir olchovli massivlarimizni vertikal holatda birlashtirmoqda  

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.hstack([r1,r2,r2,r1])  #korganingizdek bir olchovli massivlarimizni garizantal holatda birlashtirmoqda  

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  6,  7,  8,  9, 10,  1,  2,
        3,  4,  5])

### ***Qo'yboqov Mahmud 102.20 - Guruh***
